/**
 * resume-data
 * API for managing my resume data
 *
 * The version of the OpenAPI document: 2023-01-16T13:44:13Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Social } from './social';


/**
 * Details about the entry. Varies by entry type
 */
export interface EntryDetails { 
    /**
     * For education type: the degree received
     */
    degree?: string;
    /**
     * For education type: the notable-classes taken
     */
    notableClasses?: Array<string>;
    /**
     * For employment type: the position in the job
     */
    position?: string;
    /**
     * For employment type: each line is a description of one role performed in the job
     */
    duties?: Array<string>;
    /**
     * For skillhard type: a ranking from 1-5 of experience with the skill
     */
    proficiency?: number;
    /**
     * For project type: a url to a project
     */
    projectSource?: string;
    /**
     * For bio type: a list of social media objects
     */
    social?: Array<Social>;
    introduction?: Array<string>;
    subtitle?: string;
}

