/**
 * resume-data
 * API for managing my resume data
 *
 * The version of the OpenAPI document: 2023-01-16T13:44:13Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntryDetails } from './entryDetails';


export interface ResumeEntry { 
    /**
     * Approximate date the event first began
     */
    startDate: string;
    /**
     * Approximate date the event ended, or \'present\'
     */
    endDate: string;
    /**
     * The username the entry is tied to
     */
    user: string;
    details: EntryDetails;
    id: string;
    title: string;
    type: ResumeEntry.TypeEnum;
}
export namespace ResumeEntry {
    export type TypeEnum = 'education' | 'employment' | 'skillhard' | 'project' | 'bio';
    export const TypeEnum = {
        Education: 'education' as TypeEnum,
        Employment: 'employment' as TypeEnum,
        Skillhard: 'skillhard' as TypeEnum,
        Project: 'project' as TypeEnum,
        Bio: 'bio' as TypeEnum
    };
}


