import { Injectable } from '@angular/core';
import { AuthenticatorService } from '@aws-amplify/ui-angular';
import { Observable } from 'rxjs';
import { map, shareReplay } from 'rxjs/operators';
import { DefaultService, ResumeEntry, UserData } from './api/v1';
import { ResumeEntriesByType } from './models';


/**
 * Until I can generate an openapi or swagger doc that includes tags,
 * this wrapper will provide a better name for the service generated by openapi-generator-cli
 */
@Injectable({
  providedIn: 'root'
})
export class ResumeDataService {

  constructor(private service: DefaultService, private authenticator: AuthenticatorService) { }

  public getEntriesByUser(username: string): Observable<UserData> {
    return this.service.getEntriesByUser(username).pipe(
      shareReplay(1)
    );
  }

  public getEntriesByType(username: string): Observable<ResumeEntriesByType> {
    return this.getEntriesByUser(username).pipe(
      map((resp) => ResumeEntriesByType.fromResumeEntries(resp.Items))
    );
  }

  public putEntry(username: string, entry: ResumeEntry): Observable<object> {
    if (this.authenticator.user) {
      this.setToken(this.authenticator.user.getSignInUserSession().getIdToken().getJwtToken());
    }
    console.log(this.service.configuration);
    return this.service.putEntry(username, entry);
  }

  private setToken(token: string): void {
    this.service.configuration.credentials['resume-website-api-gateway-authorizer'] = token;
  }
}
